import { AuthRegisterProvider } from "@/hooks/auth/providers";
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import 'leaflet/dist/leaflet.css'

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <title>NetoFuel</title>
        <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet"
        ></link>
        
      </head>
      <body
        className={`${quicksand.variable} antialiased h-full bg-white`}
      >
        <AuthRegisterProvider>
        {children}
        </AuthRegisterProvider> 
      </body>
    </html>
  );
}
